Migration to 9.x.x (#61)
* Set version to 9.0.0

* Updated ontimize-web-ngx dependency

* Updated to TypeScript 3.8

* Angular CLI update for packages - @angular/cli@9, @angular/core@9

* @angular/cli migration - workspace-version-9
Angular Workspace migration. Update an Angular CLI workspace to version 9.

* @angular/core migration - migration-v9-dynamic-queries
Static flag migration. Removes the `static` flag from dynamic queries. As of Angular 9, the "static" flag defaults to false and is no longer required for your view and content queries. Read more about this here: https://v9.angular.io/guide/migration-dynamic-flag

* @angular/core migration - migration-v9-missing-injectable
Missing @Injectable and incomplete provider definition migration. In Angular 9, enforcement of @Injectable decorators for DI is a bit stricter and incomplete provider definitions behave differently. Read more about this here: https://v9.angular.io/guide/migration-injectable

* Fixed error TS5052: Option 'emitDecoratorMetadata' cannot be specified without specifying option 'experimentalDecorators'.

* Uninstall flex-layout

* Migrations of package '@angular/material

* Install flex-layout

* Fixed deeprecated UIEvent.initUIEvent()

* Updated version to 9.0.0

* Updated package.json

* Updated package-lock

* Updated package.json